### ISSUE TITLE
Changes in the lines

### ISSUE THREAD

**Issue by zZOGZz** [npwd-community/npwd_qb_services#5]
![image](https://user-images.githubusercontent.com/94694368/187237867-a964e15f-9e2d-4139-b69c-7af2322ad721.png)

https://github.com/npwd-community/npwd_qb_services/blob/e621a8a3d700cca8d906005d3566081613473f88/src/components/PlayersList.tsx#L50

https://github.com/npwd-community/npwd_qb_services/blob/main/src/components/PlayersList.tsx#L29

fetchNui<ServerPromiseResp>('npwd:qb-services:callPlayer', { number, job }).then((res) => {

onClick={() => handleCallPlayer(player.phoneNumber, player.job)}

**Comment by SamShanks1** [comment]
in latest release
